// <auto-generated />
namespace AndreFilho.Blog.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class create_schema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_schema));
        
        string IMigrationMetadata.Id
        {
            get { return "201605030006133_create_schema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
